### ISSUE TITLE
Packaging issue with Spring dependencies

### ISSUE THREAD

**Issue by ctranxuan** [fabric8io/vertx-maven-plugin#126]
Hello,
While packaging a Vert.x with dependencies that uses Spring, we ran the following issue when trying to start the resulting jar: 

`org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.springframework.org/schema/util]
`

**Investigations**

From our investigations, we think that:
 
- some Spring dependencies (`spring-beans`, `spring-aop`, `spring-jdbc`) declare their own `META-INF/spring.schemas` and `META-INF/spring.handlers` in which some Spring namespace handlers are declared
- these files are overwritten when using the `vertx-maven-plugin`  to package the fat jar. As there are several files with the same name and location, only one survives ("Highlander effect" ;)). As only one survives, it raises the above error about missing NamespaceHandler.

**Solution?**

We guess that adding an option to append the content of the files with the same names and locations would fix our issue. But that works for non structured files (may be, it won't work with xml files for instance).

**Reproducibility**

Please find in attachment an example that enable to reproduce the issue. In the project, run:

```
mvn clean install
java -jar target/vertx-spring-issue-1.0-SNAPSHOT.jar
```
You should get:

<details>

```
class org.apache.ignite.IgniteException: Failed to instantiate Spring XML application context [springUrl=jar:file:/home/ctranxuan/projects/misc/workspace/vertx-spring-issue/target/vertx-spring-issue-1.0-SNAPSHOT.jar!/ignite-cq.xml, err=Configuration problem: Unexpected failure during bean definition parsing
Offending resource: URL [jar:file:/home/ctranxuan/projects/misc/workspace/vertx-spring-issue/target/vertx-spring-issue-1.0-SNAPSHOT.jar!/ignite-cq.xml]
Bean ''; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.springframework.org/schema/util]
Offending resource: URL [jar:file:/home/ctranxuan/projects/misc/workspace/vertx-spring-issue/target/vertx-spring-issue-1.0-SNAPSHOT.jar!/ignite-cq.xml]
Bean ''
        -> Property 'includeEventTypes']
        at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:949)
        at org.apache.ignite.Ignition.start(Ignition.java:350)
        at org.tests.vertx.MyVerticle.start(MyVerticle.java:20)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
Caused by: class org.apache.ignite.IgniteCheckedException: Failed to instantiate Spring XML application context [springUrl=jar:file:/home/ctranxuan/projects/misc/workspace/vertx-spring-issue/target/vertx-spring-issue-1.0-SNAPSHOT.jar!/ignite-cq.xml, err=Configuration problem: 
```

</details>

We haven't attached the resulting jar (~23M), but let us know whether you need it.

**Environment**

- Java 1.8.0_73
- Maven 3.5.0
- vertx-maven-plugin: 1.0.7

We hope this helps.

[vertx-spring-issue.zip](https://github.com/fabric8io/vertx-maven-plugin/files/1036158/vertx-spring-issue.zip)

**Comment by cescoffier** [comment]
I believe I've already fixed in during my inner refactoring I've done last week. Let me try with your reproducer.

**Comment by cescoffier** [comment]
Actually not... you need SPI combination outside of `META-INF/services` (enabled by default). I will add an option for this.

**Comment by cescoffier** [comment]
@ctranxuan 

Can you tell me if this is the "expected" output:

```
May 29, 2017 5:58:35 PM java.util.logging.LogManager$RootLogger log
SEVERE: Failed to resolve default logging config file: config/java.util.logging.properties
[17:58:35]    __________  ________________
[17:58:35]   /  _/ ___/ |/ /  _/_  __/ __/
[17:58:35]  _/ // (7 7    // /  / / / _/
[17:58:35] /___/\___/_/|_/___/ /_/ /___/
[17:58:35]
[17:58:35] ver. 2.0.0#20170430-sha1:d4eef3c6
[17:58:35] 2017 Copyright(C) Apache Software Foundation
[17:58:35]
[17:58:35] Ignite documentation: http://ignite.apache.org
[17:58:35]
[17:58:35] Quiet mode.
[17:58:35]   ^-- To see **FULL** console log here add -DIGNITE_QUIET=false or "-v" to ignite.{sh|bat}
[17:58:35]
[17:58:35] OS: Mac OS X 10.12.5 x86_64
[17:58:35] VM information: Java(TM) SE Runtime Environment 1.8.0_91-b14 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.91-b14
[17:58:35] Initial heap size is 256MB (should be no less than 512MB, use -Xms512m -Xmx512m).
[17:58:35] Configured plugins:
[17:58:35]   ^-- None
[17:58:35]
[17:58:37] Message queue limit is set to 0 which may lead to potential OOMEs when running cache operations in FULL_ASYNC or PRIMARY_SYNC modes due to message queues growth on sender and receiver sides.
[17:58:37] Security status [authentication=off, tls/ssl=off]
[17:58:38] REST protocols do not start on client node. To start the protocols on client node set '-DIGNITE_REST_START_ON_CLIENT=true' system property.
[17:58:38] Failed to connect to any address from IP finder (will retry to join topology every 2 secs): [/127.0.0.1:47500, /127.0.0.1:47501, /127.0.0.1:47502, /127.0.0.1:47503, /127.0.0.1:47504, /127.0.0.1:47505, /127.0.0.1:47506, /127.0.0.1:47507, /127.0.0.1:47508, /127.0.0.1:47509]
```

**Comment by cescoffier** [comment]
(if so, just fixed it ;-))

**Comment by ctranxuan** [comment]
Yep, it looks good.
What do we have to do to make it works? I forgot to tell we have tried with the latest version of master (the one, just before reporting the issue) because we've seen some related stuff in #124.

**Comment by cescoffier** [comment]
Yes, #124 was related but not enough. I will push a fix Today. The issue requires the combination of the different Spring descriptors. By default, the plugin combines SPI provides from META-INF/services. Obviously, the Spring descriptors are not there...

**Comment by cescoffier** [comment]
@ctranxuan can you try with #127 ?

**Comment by ctranxuan** [comment]
It works like a charm :ok_hand: 
Thanks! 
So, is there any release foreseen soon? ;)

**Comment by cescoffier** [comment]
> On 30 May 2017, at 11:42, ctranxuan <notifications@github.com> wrote:
> 
> It works like a charm 👌
> Thanks!
> So, is there any release foreseen soon? ;)
> 
> 

Yes, just need to work around an issue on windows...
